### ISSUE TITLE
Failing when given surface where zmin/zmax is not a finite number

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#634]
Getting these errors when providing certain regular surfaces through `AggregatedData`:

```python
Traceback (most recent call last):
  File "/app/jobs/surface_aggregate_and_upload.py", line 133, in <module>
    main()
  File "/app/jobs/surface_aggregate_and_upload.py", line 129, in main
    job.run()
  File "/app/jobs/utils/decorators.py", line 14, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/jobs/utils/aggregation_job.py", line 31, in run
    results = self._aggregate(objects)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/jobs/utils/decorators.py", line 14, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/jobs/surface_aggregate_and_upload.py", line 74, in _aggregate
    metadata = self._generate_metadata(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/jobs/utils/aggregation_job.py", line 143, in _generate_metadata
    metadata = exd.generate_aggregation_metadata(data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/fmu/dataio/aggregation.py", line 330, in generate_aggregation_metadata
    return self.generate_metadata(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/fmu/dataio/aggregation.py", line 315, in generate_metadata
    self._generate_aggrd_metadata(obj, real_ids, uuids, compute_md5)
  File "/app/venv/lib/python3.11/site-packages/fmu/dataio/aggregation.py", line 247, in _generate_aggrd_metadata
    objdata = objectdata_provider_factory(obj=obj, dataio=etemp).get_objectdata()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/fmu/dataio/providers/objectdata/_xtgeo.py", line 75, in get_objectdata
    bbox=self.get_bbox(),
         ^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/fmu/dataio/providers/objectdata/_xtgeo.py", line 54, in get_bbox
    return meta.content.BoundingBox3D(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for BoundingBox3D
zmin
  Input should be a finite number [type=finite_number, input_value=nan, input_type=float]
    For further information visit https://errors.pydantic.dev/2.6/v/finite_number
zmax
  Input should be a finite number [type=finite_number, input_value=nan, input_type=float]
    For further information visit https://errors.pydantic.dev/2.6/v/finite_number 
```

Error comes from `fmu-dataio`, and at first glance it looks like hard crash when given surface object does not have meaningful values for `zmin` (and probably also `zmax`).

Stems from this: https://github.com/equinor/fmu-dataio/blob/3b3d4053f24245bc068c1dbabe9b92a1c173faf2/src/fmu/dataio/providers/objectdata/_xtgeo.py#L59

Note that `zmin`/`zmax` is not part of the XTgeo data model. We add them as a calculation on the fly, simply taking `.min()` and `.max()` of the values. If this method returns anything else than a `float` I guess it will not validate.

Suggested behaviour:
- When `NaN` or equivalent comes out of Numpy, return `None` and
- Allow zmin/zmax to be `None` (surface has no values, and hence no max/min can be meaningfully defined.)

**Comment by perolavsvendsen** [comment]
I think this happens when a surface containing only `NaN` is given to fmu-dataio. This can happen from time to time, and we should be robust for it.

This will recreate:

`conftest.py`
```python
@pytest.fixture(name="regsurf_nan_only", scope="module")
def fixture_regsurf_nan_only():
    """Create an xtgeo surface with only NaNs."""
    logger.debug("Ran %s", _current_function_name())
    return xtgeo.RegularSurface(ncol=12, nrow=10, xinc=20, yinc=20, values=np.nan)
```

`test_objectdata_provider_class.py`
```python
def test_objectdata_regularsurface_spec_bbox_no_min_max(regsurf_nan_only, edataobj1):
    """Derive specs and bbox for surface with nonfinite min/max values."""

    objdata = objectdata_provider_factory(regsurf_nan_only, edataobj1)
    bbox = objdata.get_bbox()
```

**Comment by perolavsvendsen** [comment]
Offline discussions

- Possibly (probably?) better that `zmin` and `zmax` is not present when not valid input
  - Will imply that `data.bbox` is sometimes a `bbox2D` and sometimes a `bbox3D`
- What about other data types? E.g. empty dataframe? 3D grid parameters? Probably only an issue for surfaces?
- Include a flag in metadata that indicates if data object "is empty".
  - What does "empty" mean?
